name: Bug Report
description: Report an Issue
body:
  - type: markdown
    attributes:
      value: |
         This is a template Bug Report Page `my project`

         [project link]: https://github.com
  - type: textarea
    id: freeform
    attributes:
      label: Describe the Issue
      placeholder: 'x happened while i was doing y'
    validations:
      required: true
