name: Feature Request
description: Suggest Something New
body:
  - type: markdown
    attributes:
      value: |
         This is a template Feature Request Page `my project`

         [project link]: https://github.com
  - type: textarea
    id: freeform
    attributes:
      label: Describe your Feature Request
      placeholder: 'I want to do x'
    validations:
      required: true
