name: Push-to-EC2

# Trigger deployment only on push to master branch
# on:
#   push:
#     branches: [master, staging, development]
on:
  pull_request:
    types: [ closed ]

jobs:
  dev-deploy:
    if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world dev
  stg-deploy:
    if: github.event.pull_request.base.ref == 'staging' && github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world staging
  prod-deploy:
    if: github.event.pull_request.base.ref == 'production' && github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world prod