name: Deploy

on:
  pull_request:
    types: [ closed ]

jobs:
  dev-deploy:
    if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world dev
  stg-deploy:
    if: github.event.pull_request.base.ref == 'staging' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world staging
  prod-deploy:
    if: github.event.pull_request.base.ref == 'production' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world prod

  second-job:
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_MESSAGE: 'Debezium Kafka Demo Deployed to xxx'
          SLACK_TITLE: Deploy Successful
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}