name: Push-to-EC2

# Trigger deployment only on push to master branch
# on:
#   push:
#     branches: [master, staging, development]
on:
  push:
    branches: [master, staging]
  pull_request:
    types:
      - closed
    branches: [production]

jobs:
  dev-deploy:
    if: github.ref == 'refs/heads/master' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world dev
  stg-deploy:
    if: github.ref == 'refs/heads/staging' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world staging
  prod-deploy:
    if: github.ref == 'refs/heads/production' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: deploy
      run: |
        echo hello world prod